<?php

use Illuminate\Support\Facades\Storage;
use function Pest\Laravel\artisan;

it('computes the sample timeline count for day seven part two', function () {
    $contents = <<<TXT
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
TXT;

    Storage::fake('public');
    Storage::disk('public')->put('day7_part2_sample.txt', $contents);

    artisan('advent-of-code:day-seven-part-two', ['file' => 'day7_part2_sample.txt'])
        ->expectsOutputToContain('40 (took')
        ->assertExitCode(0);
});