<?php

use Illuminate\Support\Facades\Storage;
use function Pest\Laravel\artisan;

it('counts splits in the sample manifold for day seven part one', function () {
    $contents = <<<TXT
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
TXT;

    Storage::fake('public');
    Storage::disk('public')->put('day7_sample.txt', $contents);

    artisan('advent-of-code:day-seven', ['file' => 'day7_sample.txt'])
        ->expectsOutputToContain('21 (took')
        ->assertExitCode(0);
});